---
#############################################################
# Trajectory settings                                       #
#############################################################

initial_time: 0.0
final_time: 100.0

# How many times to output between initial and final time
output_times: 100

initial_V1: 0.0
initial_V2: 0.8
initial_V3: 0.0

initial_X1: 5.0
initial_X2: 0.0
initial_X3: 0.0

initial_EN: 1.0

output_file: "kerr_schild_kerr_trajectory.ascii"
metadata_file: "kerr_schild_kerr_trajectory_metadata.ascii"

background_metric: "Kerr-Schild Kerr"

background_radius: 20.0
energy_threshold: 1.0

# Zero for photons, anything else for massive.
particle_type: 1

KerrSchild_Kerr_Settings:
  M: 1.0
  a: 0.5
