---
#############################################################
# Trajectory settings                                       #
#############################################################

initial_time: 0.0
final_time: 100.0

# How many times to output between initial and final time
output_times: 100

initial_V1: 0.0
initial_V2: 0.8
initial_V3: 0.0

initial_X1: -10.0
initial_X2: 0.0
initial_X3: 0.0

initial_EN: 1.0

output_file: "sks_trajectory.ascii"
metadata_file: "sks_trajectory_metadata.ascii"

background_metric: "Superimposed Kerr binary in Kerr-Schild coordinates"

background_radius: 20.0
energy_threshold: 2.0

# Zero for photons, anything else for massive.
particle_type: 1

SKS_Settings:
  M1: 1.0
  M2: 1.0
  a1: 0.5
  a2: 0.5
  b: 10.0
